// https://adventofcode.com/2022/day/9
// --- Day 9: Rope Bridge ---
// This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.

// It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.

// You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where not to step.

// Consider a rope with a knot at each end; these knots mark the head and the tail of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.

// Due to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a two-dimensional grid. Then, by following a hypothetical series of motions (your puzzle input) for the head, you can determine how the tail will move.

// Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must always be touching (diagonally adjacent and even overlapping both count as touching):

// ....
// .TH.
// ....

// ....
// .H..
// ..T.
// ....

// ...
// .H. (H covers T)
// ...
// If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:

// .....    .....    .....
// .TH.. -> .T.H. -> ..TH.
// .....    .....    .....

// ...    ...    ...
// .T.    .T.    ...
// .H. -> ... -> .T.
// ...    .H.    .H.
// ...    ...    ...
// Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:

// .....    .....    .....
// .....    ..H..    ..H..
// ..H.. -> ..... -> ..T..
// .T...    .T...    .....
// .....    .....    .....

// .....    .....    .....
// .....    .....    .....
// ..H.. -> ...H. -> ..TH.
// .T...    .T...    .....
// .....    .....    .....
// You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.

// For example:

// R 4
// U 4
// L 3
// D 1
// R 4
// D 1
// L 5
// R 2
// This series of motions moves the head right four steps, then up four steps, then left three steps, then down one step, and so on. After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a reference point):

// == Initial State ==

// ......
// ......
// ......
// ......
// H.....  (H covers T, s)

// == R 4 ==

// ......
// ......
// ......
// ......
// TH....  (T covers s)

// ......
// ......
// ......
// ......
// sTH...

// ......
// ......
// ......
// ......
// s.TH..

// ......
// ......
// ......
// ......
// s..TH.

// == U 4 ==

// ......
// ......
// ......
// ....H.
// s..T..

// ......
// ......
// ....H.
// ....T.
// s.....

// ......
// ....H.
// ....T.
// ......
// s.....

// ....H.
// ....T.
// ......
// ......
// s.....

// == L 3 ==

// ...H..
// ....T.
// ......
// ......
// s.....

// ..HT..
// ......
// ......
// ......
// s.....

// .HT...
// ......
// ......
// ......
// s.....

// == D 1 ==

// ..T...
// .H....
// ......
// ......
// s.....

// == R 4 ==

// ..T...
// ..H...
// ......
// ......
// s.....

// ..T...
// ...H..
// ......
// ......
// s.....

// ......
// ...TH.
// ......
// ......
// s.....

// ......
// ....TH
// ......
// ......
// s.....

// == D 1 ==

// ......
// ....T.
// .....H
// ......
// s.....

// == L 5 ==

// ......
// ....T.
// ....H.
// ......
// s.....

// ......
// ....T.
// ...H..
// ......
// s.....

// ......
// ......
// ..HT..
// ......
// s.....

// ......
// ......
// .HT...
// ......
// s.....

// ......
// ......
// HT....
// ......
// s.....

// == R 2 ==

// ......
// ......
// .H....  (H covers T)
// ......
// s.....

// ......
// ......
// .TH...
// ......
// s.....
// After simulating the rope, you can count up all of the positions the tail visited at least once. In this diagram, s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:

// ..##..
// ...##.
// .####.
// ....#.
// s###..
// So, there are 13 positions the tail visited at least once.

// Simulate your complete hypothetical series of motions. How many positions does the tail of the rope visit at least once?

const fs = require('fs');
const assert = require('assert');

function solveOne(string){
    const moves = string.split('\n').map(m => m.split(' ')).map(move => {
        const [dir, steps] = move
        return [dir, Number(steps)]
    })

    //First simulate the movement of Head H to know the size of the grid, then simulate again with its Tail T following H accordingly

    //We do not know the size of the grid so we will work on that first
    let grid
    let HCoord //coord are represented as an array [y, x] such as grid[y][x] is H
    let TCoord //coord are represented as an array [y, x] such as grid[y][x] is T
    //grid is initialized with only false as we are only interested in if a cell is visited or not right now
    initializeGrid()

    //make the "dance" between H and T
    moves.forEach(([direction, steps]) => {
        for(let i=0 ; i<steps ; i++){
            move(direction)
        }
    })

    let visited = 0
    //count visited
    for(let row=0 ; row<grid.length ; row++){
        for(let col=0 ; col<grid[0].length ; col++){
            if(grid[row][col] === true){
                visited++
            }
        }
    }

    // console.log(grid);
    console.log(visited);
    return visited

    //To initialize the grid, we will run our head starting from [0,0] (it doesn't mean it will stay at [0,0]) the difference between the extremities will give us the size
    function initializeGrid(){
        let X = 0
        let Y = 0
        let minX = 0
        let maxX = 0
        let minY = 0
        let maxY = 0
        moves.forEach(([direction, steps]) => {
            switch (direction) {
                case "U":
                    Y -= steps
                    break;

                case "R":
                    X += steps
                    break;

                case "D":
                    Y += steps
                    break;

                case "L":
                    X -= steps
                    break;
            
                default:
                    break;
            }

            minX = Math.min(minX, X)
            maxX = Math.max(maxX, X)
            minY = Math.min(minY, Y)
            maxY = Math.max(maxY, Y)
        })

        // console.log("minX:", minX)
        // console.log("maxX:", maxX)
        // console.log("minY:", minY)
        // console.log("maxY:", maxY)
        const nLine = Math.abs(minY) + maxY + 1
        const nCol = Math.abs(minX) + maxX + 1
        grid = Array.from({length : nLine}, (line) => Array(nCol).fill(false))
        //initialize H and T where they will never hop out of the grid
        HCoord = [Math.abs(minY), Math.abs(minX)]
        TCoord = [Math.abs(minY), Math.abs(minX)]
        //initialize start as visited
        grid[Math.abs(minY)][Math.abs(minX)] = true
        // console.log(grid);
    }


    function move(direction){
        moveH(direction)
        moveT()
    }

    function moveH(direction){
        switch (direction) {
            case 'U':
                HCoord[0] -= 1
                break;

            case 'R':
                HCoord[1] += 1
                break;

            case 'D':
                HCoord[0] += 1
                break;

            case 'L':
                HCoord[1] -= 1
                break;
        
            default:
                break;
        }
    }

    function moveT(){
        //if T is in the Moore neighborhood (or H=T) of H, don't move
        if(isMooreNeighborhood(HCoord, TCoord)){
            return
        }else{
            //move on the same line or col
            if((HCoord[0] === TCoord[0]) || (HCoord[1] === TCoord[1])){
                TCoord = [Math.floor((HCoord[0]+TCoord[0])/2) , Math.floor((HCoord[1]+TCoord[1])/2)]
                grid[TCoord[0]][TCoord[1]] = true
            }else{
                //move diagonally
                let yT = (HCoord[0] > TCoord[0]) ? TCoord[0]+1 : TCoord[0]-1
                let xT = (HCoord[1] > TCoord[1]) ? TCoord[1]+1 : TCoord[1]-1
                TCoord = [yT ,xT]
                grid[yT][xT] = true
            }
        }
    }
    
    //moore is a the 8 cells surrounding a cell (or A=B)
    function isMooreNeighborhood(pointA, pointB){
        const numRows = grid.length;
        const numCols = grid[0].length;

        const [yA, xA] = pointA;
        const [yB, xB] = pointB;

        // Check if points A and B are within the bounds of the grid
        if (yA < 0 || yA >= numRows || xA < 0 || xA >= numCols ||
            yB < 0 || yB >= numRows || xB < 0 || xB >= numCols) {
            return false;
        }

        // Calculate the absolute difference in x and y coordinates
        const diffX = Math.abs(xA - xB);
        const diffY = Math.abs(yA - yB);

        // Check if A is within the Moore neighborhood of B or if A equals B
        return (diffX <= 1 && diffY <= 1) || (xA === xB && yA === yB);
    }
}

// (() => {
// const data = fs.readFileSync(__dirname + '/input.txt').toString();
// console.log(solveOne(data));

// assert.deepStrictEqual(solveOne(`R 4
// U 4
// L 3
// D 1
// R 4
// D 1
// L 5
// R 2`), 13);

// })();
// CORRECT ANSWER : 6494

//=================================================
// --- Part Two ---
// A rope snaps! Suddenly, the river is getting a lot closer than you remember. The bridge is still there, but some of the ropes that broke are now whipping toward you as you fall through the air!

// The ropes are moving too quickly to grab; you only have a few seconds to choose how to arch your body to avoid being hit. Fortunately, your simulation can be extended to support longer ropes.

// Rather than two knots, you now must simulate a rope consisting of ten knots. One knot is still the head of the rope and moves according to the series of motions. Each knot further down the rope follows the knot in front of it using the same rules as before.

// Using the same series of motions as the above example, but with the knots marked H, 1, 2, ..., 9, the motions now occur as follows:

// == Initial State ==

// ......
// ......
// ......
// ......
// H.....  (H covers 1, 2, 3, 4, 5, 6, 7, 8, 9, s)

// == R 4 ==

// ......
// ......
// ......
// ......
// 1H....  (1 covers 2, 3, 4, 5, 6, 7, 8, 9, s)

// ......
// ......
// ......
// ......
// 21H...  (2 covers 3, 4, 5, 6, 7, 8, 9, s)

// ......
// ......
// ......
// ......
// 321H..  (3 covers 4, 5, 6, 7, 8, 9, s)

// ......
// ......
// ......
// ......
// 4321H.  (4 covers 5, 6, 7, 8, 9, s)

// == U 4 ==

// ......
// ......
// ......
// ....H.
// 4321..  (4 covers 5, 6, 7, 8, 9, s)

// ......
// ......
// ....H.
// .4321.
// 5.....  (5 covers 6, 7, 8, 9, s)

// ......
// ....H.
// ....1.
// .432..
// 5.....  (5 covers 6, 7, 8, 9, s)

// ....H.
// ....1.
// ..432.
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// == L 3 ==

// ...H..
// ....1.
// ..432.
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// ..H1..
// ...2..
// ..43..
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// .H1...
// ...2..
// ..43..
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// == D 1 ==

// ..1...
// .H.2..
// ..43..
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// == R 4 ==

// ..1...
// ..H2..
// ..43..
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// ..1...
// ...H..  (H covers 2)
// ..43..
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// ......
// ...1H.  (1 covers 2)
// ..43..
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// ......
// ...21H
// ..43..
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// == D 1 ==

// ......
// ...21.
// ..43.H
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// == L 5 ==

// ......
// ...21.
// ..43H.
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// ......
// ...21.
// ..4H..  (H covers 3)
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// ......
// ...2..
// ..H1..  (H covers 4; 1 covers 3)
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// ......
// ...2..
// .H13..  (1 covers 4)
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// ......
// ......
// H123..  (2 covers 4)
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// == R 2 ==

// ......
// ......
// .H23..  (H covers 1; 2 covers 4)
// .5....
// 6.....  (6 covers 7, 8, 9, s)

// ......
// ......
// .1H3..  (H covers 2, 4)
// .5....
// 6.....  (6 covers 7, 8, 9, s)
// Now, you need to keep track of the positions the new tail, 9, visits. In this example, the tail never moves, and so it only visits 1 position. However, be careful: more types of motion are possible than before, so you might want to visually compare your simulated rope to the one above.

// Here's a larger example:

// R 5
// U 8
// L 8
// D 3
// R 17
// D 10
// L 25
// U 20
// These motions occur as follows (individual steps are not shown):

// == Initial State ==

// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ...........H..............  (H covers 1, 2, 3, 4, 5, 6, 7, 8, 9, s)
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................

// == R 5 ==

// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ...........54321H.........  (5 covers 6, 7, 8, 9, s)
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................

// == U 8 ==

// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ................H.........
// ................1.........
// ................2.........
// ................3.........
// ...............54.........
// ..............6...........
// .............7............
// ............8.............
// ...........9..............  (9 covers s)
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................

// == L 8 ==

// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ........H1234.............
// ............5.............
// ............6.............
// ............7.............
// ............8.............
// ............9.............
// ..........................
// ..........................
// ...........s..............
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................

// == D 3 ==

// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// .........2345.............
// ........1...6.............
// ........H...7.............
// ............8.............
// ............9.............
// ..........................
// ..........................
// ...........s..............
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................

// == R 17 ==

// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ................987654321H
// ..........................
// ..........................
// ..........................
// ..........................
// ...........s..............
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................

// == D 10 ==

// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ...........s.........98765
// .........................4
// .........................3
// .........................2
// .........................1
// .........................H

// == L 25 ==

// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ...........s..............
// ..........................
// ..........................
// ..........................
// ..........................
// H123456789................

// == U 20 ==

// H.........................
// 1.........................
// 2.........................
// 3.........................
// 4.........................
// 5.........................
// 6.........................
// 7.........................
// 8.........................
// 9.........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ...........s..............
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................

// Now, the tail (9) visits 36 positions (including s) at least once:

// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// ..........................
// #.........................
// #.............###.........
// #............#...#........
// .#..........#.....#.......
// ..#..........#.....#......
// ...#........#.......#.....
// ....#......s.........#....
// .....#..............#.....
// ......#............#......
// .......#..........#.......
// ........#........#........
// .........########.........
// Simulate your complete series of motions on a larger rope with ten knots. How many positions does the tail of the rope visit at least once?

function solveTwo(string){
    const moves = string.split('\n').map(m => m.split(' ')).map(move => {
        const [dir, steps] = move
        return [dir, Number(steps)]
    })

    //First simulate the movement of Head H to know the size of the grid, then simulate again with its Tail 1 to 9 following their respective predecessors accordingly

    //We do not know the size of the grid so we will work on that first
    let grid
    let coords = {} // H, 1 to 9 represented as an array coord['H', 1 to 9] = [y, x] such as grid[y][x] is H, 1 to 9
    //grid is initialized with only false as we are only interested in if a cell is visited or not right now
    initializeGrid()

    //make the "dance" between H, 1 to 9
    moves.forEach(([direction, steps]) => {
        for(let i=0 ; i<steps ; i++){
            move(direction)
        }
    })

    let visited = 0
    //count visited
    for(let row=0 ; row<grid.length ; row++){
        for(let col=0 ; col<grid[0].length ; col++){
            if(grid[row][col] === true){
                visited++
            }
        }
    }

    // console.log(grid);
    console.log(visited);
    return visited

    //To initialize the grid, we will run our head starting from [0,0] (it doesn't mean it will stay at [0,0]) the difference between the extremities will give us the size
    function initializeGrid(){
        let X = 0
        let Y = 0
        let minX = 0
        let maxX = 0
        let minY = 0
        let maxY = 0
        moves.forEach(([direction, steps]) => {
            switch (direction) {
                case "U":
                    Y -= steps
                    break;

                case "R":
                    X += steps
                    break;

                case "D":
                    Y += steps
                    break;

                case "L":
                    X -= steps
                    break;
            
                default:
                    break;
            }

            minX = Math.min(minX, X)
            maxX = Math.max(maxX, X)
            minY = Math.min(minY, Y)
            maxY = Math.max(maxY, Y)
        })

        // console.log("minX:", minX)
        // console.log("maxX:", maxX)
        // console.log("minY:", minY)
        // console.log("maxY:", maxY)
        const nLine = Math.abs(minY) + maxY + 1
        const nCol = Math.abs(minX) + maxX + 1
        grid = Array.from({length : nLine}, (line) => Array(nCol).fill(false))
        //initialize H, 1 to 9 where they will never hop out of the grid
        coords['H'] = [Math.abs(minY), Math.abs(minX)]
        for(let i=1 ; i<=9 ; i++){
            coords[i] = [Math.abs(minY), Math.abs(minX)]
        }
        //initialize start as visited
        grid[Math.abs(minY)][Math.abs(minX)] = true
        // console.log(grid);
    }


    function move(direction){
        moveH(direction)
        moveTail()
    }

    function moveH(direction){
        switch (direction) {
            case 'U':
                coords['H'][0] -= 1
                break;

            case 'R':
                coords['H'][1] += 1
                break;

            case 'D':
                coords['H'][0] += 1
                break;

            case 'L':
                coords['H'][1] -= 1
                break;
        
            default:
                break;
        }
    }

    function moveTail(){ //tail is numbers from 1 to 9, only 9 will mark visited as true
        //move 1 element considering its predecessor (move 1 considering H, move 3 considering 2, etc.)
        for(let i=0 ; i<9 ; i++){
            let ACoord = i===0 ? coords['H'] : coords[i]
            let BCoord = coords[i+1]
            //if A is in the Moore neighborhood (or A=B) of B, don't move
            if(isMooreNeighborhood(ACoord, BCoord)){
                return
            }else{
                //move on the same line or col
                if((ACoord[0] === BCoord[0]) || (ACoord[1] === BCoord[1])){
                    coords[i+1] = [Math.floor((ACoord[0]+BCoord[0])/2) , Math.floor((ACoord[1]+BCoord[1])/2)]
                    //update visited if element 9 of tail
                    if(i+1===9){
                        grid[coords[i+1][0]][coords[i+1][1]] = true
                    }
                }else{
                    //move diagonally
                    let yB = (ACoord[0] > BCoord[0]) ? BCoord[0]+1 : BCoord[0]-1
                    let xB = (ACoord[1] > BCoord[1]) ? BCoord[1]+1 : BCoord[1]-1
                    coords[i+1] = [yB ,xB]
                    //update visited if element 9 of tail
                    if(i+1===9){
                        grid[yB][xB] = true
                    }
                }
            }
        }
    }
    
    //moore is a the 8 cells surrounding a cell (or A=B)
    function isMooreNeighborhood(pointA, pointB){
        const numRows = grid.length;
        const numCols = grid[0].length;

        const [yA, xA] = pointA;
        const [yB, xB] = pointB;

        // Check if points A and B are within the bounds of the grid
        if (yA < 0 || yA >= numRows || xA < 0 || xA >= numCols ||
            yB < 0 || yB >= numRows || xB < 0 || xB >= numCols) {
            return false;
        }

        // Calculate the absolute difference in x and y coordinates
        const diffX = Math.abs(xA - xB);
        const diffY = Math.abs(yA - yB);

        // Check if A is within the Moore neighborhood of B or if A equals B
        return (diffX <= 1 && diffY <= 1) || (xA === xB && yA === yB);
    }
}

(() => {
    const data = fs.readFileSync(__dirname + '/input.txt').toString();
    console.log(solveTwo(data));
    
assert.deepStrictEqual(solveTwo(`R 5
U 8
L 8
D 3
R 17
D 10
L 25
U 20`), 36);

})();
//CORRECT ANSWER : 2691